### PR TITLE
add barvinok

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by inducer** [comment]
Thanks for proposing this. That said, I am not convinced that this is necessary or a good idea. The licensing on barvinok is fairly restrictive, and I definitely would not like to pick up an accidental dependency on any of this stuff. So if it happens at all, I think it would be best to have it as part of a separate package.

**Comment by matthiasdiener** [comment]
Should this be just a separate installable package, islpy-barvinok (or so)? Is there a way to depend on a pypi package (pcpp in this case) that does not have a conda package available?

**Comment by isuruf** [comment]
> Is there a way to depend on a pypi package (pcpp in this case) that does not have a conda package available? (cc: @isuruf)

Nope. You'll have to add `pcpp` as a conda package.

**Comment by inducer** [comment]
> Should this be just a separate installable package, islpy-barvinok (or so)?

If we do it, then yes. There exists a way to have multiple "outputs" from a single conda recipe.

**Review by isuruf — COMMENTED** [review]
This is not splitting off. This is creating a new package that conflicts `islpy`. To properly split off islpy-barvinok, you need to change islpy so that the barvinok parts are in a separate python submodule and then that submodule can live in `islpy-barvinok`.

**Comment by isuruf** [comment]
Implemented with https://github.com/conda-forge/islpy-feedstock/pull/31

**Pull request closed without merging**
